chore: release v5.1.0
salesforce/sfdx-lwc-jest pull request #376
Opened 2024-06-28 14:36 UTC by wjhsf

* Removed the Salesforce source API version dependency.
  * The `--skipApiVersion` flag is now deprecated, and has no functionality.
* Added a stub to support the `lightning/platformWorkspaceApi` module.
* Updated the default jest config to inherit from `@lwc/jest-preset`.
  * TypeScript files should now be supported without additional configuration.

2024-06-28 14:55 UTC, ravijayaramappa approved these changes

2024-06-28 16:31 UTC, nolanlawson approved these changes

2024-07-01 19:57 UTC, nolanlawson requested changes
This is now 6.0.0

2024-07-01 19:58 UTC, nolanlawson approved these changes
Oh my bad, you reverted the LWC v7 bump in #377

2024-07-01 19:59 UTC, merged